name: eljuego
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.4
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.6
  fpdart: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
